{application,venus,
             [{registered,[]},
              {description,"venus"},
              {applications,[kernel,stdlib,elixir,logger,ranch]},
              {mod,{'Elixir.Venus',[]}},
              {vsn,"0.0.1"},
              {modules,['Elixir.Venus','Elixir.Venus.Codec',
                        'Elixir.Venus.Listener','Elixir.Venus.Protocol',
                        'Elixir.Venus.Supervisor','Elixir.Venus.World']}]}.